# Generated by Django 5.0.6 on 2026-09-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('exam', 'Exam / Test'), ('holiday', 'Holiday'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('other', 'Other')], default='academic', max_length=20)),
                ('programme', models.CharField(choices=[('UG', 'UG (Under Graduate)'), ('PG', 'PG (Post Graduate)'), ('BOTH', 'Both UG & PG')], default='BOTH', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(help_text='e.g. 2025-26', max_length=20)),
                ('is_next_year', models.BooleanField(default=False, help_text='Plan for next academic year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('staff', 'Staff Meeting'), ('parent', 'Parent–Teacher Meeting'), ('department', 'Department Meeting'), ('other', 'Other')], default='staff', max_length=20)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('programme', models.CharField(choices=[('UG', 'UG (Under Graduate)'), ('PG', 'PG (Post Graduate)'), ('BOTH', 'Both UG & PG')], default='BOTH', max_length=10)),
                ('invited_teachers', models.TextField(blank=True, help_text='Leave blank = all teachers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['meeting_date', 'meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(help_text='Teacher ID from teachers.json', max_length=50)),
                ('teacher_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-assigned_date', 'teacher_name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=200)),
                ('teacher_id', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=200)),
                ('subject_id', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('hour', models.CharField(choices=[('1', '1st Hour'), ('2', '2nd Hour'), ('3', '3rd Hour'), ('4', '4th Hour'), ('5', '5th Hour'), ('6', '6th Hour'), ('7', '7th Hour'), ('8', '8th Hour')], max_length=5)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.CharField(blank=True, default='2025-26', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_name', 'day', 'hour'],
                'unique_together': {('class_id', 'day', 'hour', 'academic_year')},
            },
        ),
    ]
