# Generated by Django 5.0.6 on 2026-09-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='hour',
            field=models.CharField(choices=[('1', '1st Hour  (09:00–10:00)'), ('2', '2nd Hour  (10:00–11:00)'), ('3', '3rd Hour  (11:15–12:15)'), ('4', '4th Hour  (12:15–13:15)'), ('5', '5th Hour  (14:00–15:00)'), ('6', '6th Hour  (15:00–16:00)')], max_length=5),
        ),
    ]
