# Generated by Django 5.0.6 on 2026-09-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_timetableslot_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='hour',
            field=models.CharField(choices=[('1', '1st Hour  (9:00–10:00 AM)'), ('2', '2nd Hour  (10:00–11:00 AM)'), ('3', '3rd Hour  (11:15 AM–12:15 PM)'), ('4', '4th Hour  (12:15–1:15 PM)'), ('5', '5th Hour  (2:00–3:00 PM)'), ('6', '6th Hour  (3:00–4:00 PM)')], max_length=5),
        ),
    ]
