# Generated by Django 5.0.6 on 2026-09-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_timetableslot_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('circular', 'Circular'), ('notice', 'Notice'), ('minutes', 'Meeting Minutes'), ('report', 'Report'), ('policy', 'Policy'), ('syllabus', 'Syllabus'), ('result', 'Result'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='official_docs/')),
                ('file_name', models.CharField(blank=True, max_length=300)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('uploaded_by', models.CharField(default='HOD', max_length=200)),
                ('academic_year', models.CharField(blank=True, default='2025-26', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
