# Generated by Django 5.0.6 on 2026-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_officialdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(help_text='Name of the class teacher', max_length=200)),
                ('academic_year', models.CharField(default='2025-26', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_name'],
                'unique_together': {('class_id', 'academic_year')},
            },
        ),
    ]
